"<introductoryMsg>\n"
+ "package <packageName>;\n"
+ "import android.support.v8.renderscript.*;\n"
+ "<imports:{var|import <var.libraryName>;}; separator=\"\\n\">\n"
+ "public final class ParallelMERendersScript_<className> implements ParallelMERuntime_<className> {\n"
+ "\tprotected RenderScript $mRS;\n"
+ "\tprotected <kernelName> $rsKernel;\n"
+ "\tprotected <allocations>;\n\n"
+ "\tpublic ParallelMERendersScript_<className>(RenderScript $mRs) {\n"
+ "\t\tthis.$mRS = $mRs;\n"
+ "\t\tthis.$rsKernel = new <kernelName>();\n"
+ "\t}\n\n"
+ "\tpublic boolean isValid() {\n"
+ "\t\treturn this.$rsKernel != null;\n"
+ "\t}\n\n"
+ "\t<publicMethods:{var|public <var.returnType> <var.name>(<var.params>) \\{\n<var.body>\n}}; separator=\"\\n\\n\">\n"
+ "}\n"